install.packages("glmnet")
library(glmnet)
install.packages("caTools")
library(caTools)
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
install.packages("CHAID", repos="http://R-Forge.R-project.org")
library(CHAID)
install.packages("forecast")
library(forecast)
install.packages("party")
library(party)
install.packages("partykit")
library(partykit)
install.packages("amap")
library(amap)
install.packages("rpart")
install.packages("RGtk2")
y
library(RGtk2)
install.packages('foreach')

